s=str(input("Dați șirul de caractere:"))
s=s.upper() 
a=s.count('A')
b=s.replace('A','*')
c=s.replace('B','')
d=s.count('MA')
e=s.replace('MA','TA')
f=s.replace('TO','')
print ('a. A apare de:',a,'ori')
print ('b. Șirul fără A -> * :',b)
print ('c. Șirul fără B:',c)
print ('d. MA apare de:',d,'ori')
print ('e. Șirul MA -> TA:',e)
print ('f. Șirul fără TO:',f)
print ('g. Șirul invers:',s[::-1])
